### ISSUE TITLE
开发者工具打不开项目

### ISSUE THREAD

**Issue by Luffyying** [Mocha-L/Fitness_wxApp#1]
请教一下，将下载下来的程序用开发者工具打开，它提示用微信登录，才可以打开。

**Comment by Mocha-L** [comment]
本身微信的开发者工具是需要微信登录的
使用自己的微信扫码登录
然后无appid打开 应该是可以体验的
你试下

**Comment by Luffyying** [comment]
可以打开了，体验状态，多谢！
