### ISSUE TITLE
在it120上的架设部署使用到了哪些API？

### ISSUE THREAD

**Issue by weishubaoforwork** [Mocha-L/Fitness_wxApp#2]
在it120上的架设部署使用到了哪些API？还有就是CMS下的分级可以给一下吗？在分教练，推荐文章和实拍图片时候不懂你的架构

**Comment by Mocha-L** [comment]
@weishubaoforwork 
![image](https://user-images.githubusercontent.com/24688287/36715743-80f2e222-1bd2-11e8-8b12-c818e22a0c31.png)
![image](https://user-images.githubusercontent.com/24688287/36715780-a8079db2-1bd2-11e8-8053-265d260ec017.png)
![image](https://user-images.githubusercontent.com/24688287/36715797-b72f604a-1bd2-11e8-8108-6dd7971c7219.png)
不知道这几张图能不能解决你的问题
如果还有疑问的话，请联系我个人微信号：TTF_TTF

**Comment by weishubaoforwork** [comment]
已经解决了。谢谢！
